### ISSUE TITLE
commandline usage

### ISSUE THREAD

**Issue by timoxley** [pthrasher/snockets#15]
Would be good to use this from the commandline. I'm trying to bundle up files that don't necessarily belong to a node project, and a simple `snockets` command would be sweet

**Comment by jfrux** [comment]
+1

**Comment by jfrux** [comment]
FYI, I've began working on a CLI for this.  I'll keep you posted.

**Comment by pthrasher** [comment]
@joshuairl Anything ever come of this?

**Comment by pthrasher** [comment]
This will be added in 2.x sometime. I'm closing this issue for now.
