### ISSUE TITLE
Support for require_self

### ISSUE THREAD

**Issue by emilecantin** [pthrasher/snockets#18]
Hi,

It would be really nice for snockets to support the require_self directive:

https://github.com/sstephenson/sprockets#the-require_self-directive

**Comment by denysonique** [comment]
yes, this would be very useful, especially when initializing a namespace in the requiring file

**Comment by prabirshrestha** [comment]
+1

**Comment by vjpr** [comment]
+1

**Comment by lentg** [comment]
+1

**Comment by ajacksified** [comment]
+1

**Comment by jfrux** [comment]
+1

**Comment by InfinitiesLoop** [comment]
-6

**Comment by vjpr** [comment]
Check out [Mincer](https://github.com/nodeca/mincer) - a direct port of Sprockets.

**Comment by jfrux** [comment]
Ya mincer is actively developed and works identical to sprockets.
I'm porting to CF as well.

**Comment by tmikoss** [comment]
+1

**Comment by smalluban** [comment]
+1

**Comment by ajacksified** [comment]
fwiw, I moved to [Mincer](https://github.com/nodeca/mincer) and later to [Browserify](https://github.com/substack/node-browserify) with the base less precompiler. Browserify ended up being a much cleaner solution.

**Comment by smalluban** [comment]
In connect-assets snockets is used for compile js, very useful module. I was trying to force loading first file, then required. Without require_self it will not work. 

Moving to another tool will take to much time.

**Comment by pthrasher** [comment]
I like this directive. It's a potential candidate for a future release, but not the upcoming 2.0 release.

**Comment by emilecantin** [comment]
I don't use snockets anymore, so I'll go ahead and close the issue.
