### ISSUE TITLE
compilers[x].match needed?

### ISSUE THREAD

**Issue by iangreenleaf** [pthrasher/snockets#19]
All the examples of the compilers hash include a `match` key, [like here](https://github.com/TrevorBurnham/snockets/blob/master/src/snockets.coffee#L258):

``` coffee-script
module.exports.compilers = compilers =
  coffee:
    match: /\.js$/
    compileSync: ...
```

But AFAICT that's never used. Is there a reason for it to be there?

**Comment by pthrasher** [comment]
As more compilers are added, we'll need to ensure someone didn't pass a require for an unsupported file type to be compiled into the .js chain. There's currently no check in place, but this is planned to be implemented in 2.0.
