### ISSUE TITLE
'require' parsing is broken

### ISSUE THREAD

**Issue by hugovincent** [pthrasher/snockets#2]
_(Copy/pasted from closed connect-assets issue #20)._
While I can't seem to produce a stand-alone test case, I have found in my application that:

```
#= require dep1 dep2 dep3
```

works (generates correct dependency tags and order in generated output), whereas:

```
#= require dep1
#= require dep2
#= require dep3
```

does not. I will keep trying to find a small test case that exhibits this problem.

**Comment by TrevorBurnham** [comment]
That's very odd. Looking at the loop...

```
for directive in parseDirectives(@cache[filePath].data.toString 'utf8')
  words = directive.replace(/['"]/g, '').split /\s+/
  [command, relPaths...] = words

  switch command
    when 'require'
      require relPath for relPath in relPaths
    when 'require_tree'
      for relPath in relPaths
        requireTree path.join path.dirname(filePath), relPath
```

...it seems like

```
#= require dep1 dep2 dep3
```

should be precisely equivalent to

```
#= require dep1
#= require dep2
#= require dep3
```

insofar as either translates into the function calls `require 'dep1'`, `require 'dep2'`, and `require 'dep3'`, in that order.

Please keep trying to find a small test case.

**Comment by aearly** [comment]
I just ran into this issue.  The gist of the error case:

 app.js:

```
//= require model/model
//= require view/view
//= require router
...
```

view/view.js:

```
//= require ViewA
//= require ViewB
....code follows....
```

The contents `view/ViewA.js` are included in the concatenated file, but the contents of `view/ViewB.js` are not.  Declaring the `require`s as follows worked:

```
//= require ViewA ViewB
```

**Comment by litek** [comment]
I experienced the same problem, and after digging a bit I discovered snockets was only parsing unix newlines. I just converted my files (which should have been using \n from the start anyway), but I guess it might be worth considering supporting \r\n.

Relevant section here: [snockets.coffee:256](https://github.com/TrevorBurnham/snockets/blob/master/src/snockets.coffee#L256)

**Comment by TrevorBurnham** [comment]
Ahhh, that explains it. Probably easiest to just do a global replace of `\r\n` with `\n` on all input strings, right?

**Comment by TrevorBurnham** [comment]
Any trailing whitespace at the end of the line would create the same issue, so I added the line

```
code = code.replace /[\r\t ]+$/gm, '\n'
```

Please give the master branch a whirl and let me know if it works before I tag it.

**Comment by litek** [comment]
Looks like multiple linebreaks also creates the same issue, so I reckon the whitespace should be replaced with nothing rather than \n.

Or perhaps it would be better to to actually allow multiple linebreaks:

``` coffeescript
HEADER = ///
(?:
  (\#\#\# .* \#\#\#\n*) |
  (// .* \n*) |
  (\# .* \n*)
)+
///
```

**Comment by TrevorBurnham** [comment]
Good point. Change made in ec38ae5e75.
