### ISSUE TITLE
Upgrade Dependencies

### ISSUE THREAD

**Issue by scien** [pthrasher/snockets#37]
undercore:1.4.3 - things look good
coffee-script:1.4.0 - 4 tests fail after updating
uglify-js:2.2.3 - 2 test fail after updating
update all - 6 tests fail (so at least they're independent)

new minify api looks like...

```
minify = (js) ->
  result = uglify_js.minify js, {fromString: true}
  result.code
```

**Comment by pthrasher** [comment]
fixed in #43
