### ISSUE TITLE
precompiler

### ISSUE THREAD

**Issue by printercu** [pthrasher/snockets#38]
i've been thinking of thing that would concat js files using config files. so that you can put several config files into dir & they all woultd be processed. usual files with `#= require` could be used as this config files.

i've made this:

``` coffee
fs    = require 'fs'
path  = require 'path'
flow  = require 'flow'
Snockets = require 'snockets'
snockets = new Snockets()

module.exports = (params, callback) ->
  if 'function' == typeof params
    [params, callback] = [{}, params]
  params.snockets ||= './snockets'
  params.targets  ||= './js'
  params.sources  ||= './source'

  flow.exec(
    -> fs.readdir params.snockets, @
    (err, files) ->
      for file in files
        ext = path.extname file
        continue unless ext in ['.js', '.coffee']
        basename = path.basename file, ext
        minify = '.min' == path.extname basename
        cb_file = @MULTI()
        snockets.getConcatenation file, minify: minify, (err, js) ->
          return cb_file err if err
          target = "#{params.targets}/#{basename}.js"
          fs.writeFile js, target, cb_file
      true
    (results) ->
      callback flow.anyError results
  )
```

it can be used like this

``` coffee
snockets_compiler = require 'my_module'

snockets_compiler (err) -> console.log 'finished!' #default opts

snockets_compiler
  snockets: '/my/config/is/here'
  sources: '/take/sources/here'
  targets: '/put/results/there'
  (err) -> console.log 'done'
```

but i can't find how to set sources dir. Is it possible to make snockets to take required files not relatively to current file but to specific directory?

**Comment by pthrasher** [comment]
I think this is a great idea, and I actually have a similar setup myself, but it's a bit beyond the scope of snockets. I think having a tool to do this (like the one you've written) is the best way to go.

**Comment by printercu** [comment]
Already forgot about this issue)
I had been practicing coffeescript and 've made my own implementation. I focused on use with grunt and implemented only async mode. It has simplified code a lot.

About the compiler. I think it's not so complex and having separate package for it is just unnecessary. So I've included it in a package and can access with `require 'nrockets/compiler'`.
