### ISSUE TITLE
#= require ../script

### ISSUE THREAD

**Issue by ghost** [pthrasher/snockets#6]
I'm not pretty sure, but `#= require ../script` seems not to work.

**Comment by lynns** [comment]
I'm running into this problem as well.  Inclusion of a ../ in your path will not resolve correctly.

**Comment by freewil** [comment]
+1

**Comment by freewil** [comment]
This was actually fixed in 0d9be6818a9096cdb7b2f9d28961871aa2e61744

@TrevorBurnham can we get a new release?

**Comment by TrevorBurnham** [comment]
Done, tagged current master as 1.3.4. Sorry for the delay.

**Comment by freewil** [comment]
Excellent, thank you!
